[package]
name = "mimalloc-rich"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "High-level bindings to the mimalloc allocator"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[test]]
name = "hashbrown"
required-features = ["allocator-api2-02"]

[dependencies]
mimalloc-rich-sys.workspace = true
thiserror = "2"

# Support all versions of allocator-api2, starting at v0.2
# These are optional, but enabled default using the `allocator-api2-all` feature.

allocator-api2-02 = { package = "allocator-api2", version = "0.2", default-features = false, optional = true }
allocator-api2-03 = { package = "allocator-api2", version = "0.3", default-features = false, optional = true }
allocator-api2-04 = { package = "allocator-api2", version = "0.4", default-features = false, optional = true }

[dev-dependencies]
hashbrown = "0.17"

[build-dependencies]
rustversion = "1"

[features]
default = ["allocator-api2-all", "debug-if-debug", "vendored"]
# Enable all supported version of allocator-api2
allocator-api2-all = ["allocator-api2-02", "allocator-api2-03", "allocator-api2-04"]
# Enable debug mode unconditionally
debug = ["mimalloc-rich-sys/debug"]
# Enable debug mode whenever cfg(debug_assertions) is enabled
debug-if-debug = ["mimalloc-rich-sys/debug-if-debug"]
# Declare MiMalloc as the #[global_allocator]
declare-global-allocator = []
# Performs nightly specific optimizations
nightly = []
# Support the nightly allocator api
nightly-allocator-api = []
# Statically link against a vendored mimalloc
#
# This is currently required by mimalloc-sys-rich
vendored = ["mimalloc-rich-sys/vendored"]

[lints]
workspace = true
