[package]
name = "mimalloc-rich-sys"
# This version should stay mostly in sync with the main crate version.
# We add build tag to indicate what the native library version is.
# This mirrors libgit2-sys behavior
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Raw binidngs to the mimalloc library"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.cargo-shear]
ignored = [
    # cargo-shear cannot see these usages as they are hidden behind version_info! macro
    "mimalloc-rich-src-v2",
    "mimalloc-rich-src-v3",
]

[build-dependencies]
anyhow = "1"
# If we ever switch from bindgen to manual bindings,
# use the ctest crate to ensure they match.
bindgen.workspace = true
cfg-if = "1"

# vendored code & common build logic

mimalloc-rich-src-build.workspace = true
mimalloc-rich-src-v2 = { workspace = true, optional = true }
mimalloc-rich-src-v3 = { workspace = true, optional = true }

[features]
default = ["debug-if-debug", "vendored-mimalloc"]
# Enable debug mode unconditionally
debug = []
# When debug mode is enabled, perform even more checks
debug-full = []
# Enable debug mode whenever cfg(debug_assertions) is enabled
debug-if-debug = []
# Force use of mimalloc v2
force-mimalloc-v2 = []
# Force use of mimalloc v3
force-mimalloc-v3 = ["dep:mimalloc-rich-src-v3"]
# Override the C-library malloc function (off by default)
#
# For compatibility reasons, it is usually best to leave this off.
# Instead, set the rust global allocator by enabling `mimalloc-rich/declare-global-allocator`.
override-libc-malloc = []
# Enable support for Address Sanitizer
# Unlike the valgrind feature, this requires ASAN library to be present
sanitize-address = []
# Secure mode
secure = []
# Enable the `mi_visit_abandoned` flag at compile time.
#
# This flag is not documented by mimalloc in its camke file,
# so may not be fully supported
unstable-enable-visit-abandoned = []
# Enable support for valgrind, enabled by default if 'debug' is enabled.
# Does nothing when valgrind is not being used
valgrind = []
# Statically link against vendored mimalloc (default version)
#
# Currently, this is the only supported linking option
# TODO: Rename this to `vendored` for consistencty with `mimalloc-rich`
vendored-mimalloc = ["dep:mimalloc-rich-src-v2"]

[lints]
workspace = true
